### ISSUE TITLE
Hood Fan Speed Control does not work

### ISSUE THREAD

**Issue by DonutEspresso** [thoukydides/homebridge-homeconnect#185]
### Description of Issue

The slider to control the hood's fan speed no longer works. 

Notably, you can set power on/off for the fan, and it will automatically set the speed to 50%. The light control also works with no issues. 

### Expected Behaviour

Previously, if the hood fan was off, setting a speed would both turn on the fan, and set the appropriate speed. Now, the speed slider does nothing. The slider does not do anything, regardless of whether the accessory has been turned on first. 

### Steps to Reproduce

Attempting to use the speed slider to trigger on/off the fan will do nothing. In HomeKit, the UI will show a "no response" message under the accessory name. In the Homebridge UI, nothing happens. 

### Plugin Version

v0.33.0

### Environment

- OS: Ubuntu 20.04
- Node: 20.10.0
- Homebridge: 1.7.0

### Home Connect Appliance(s)

Wall Hood HMWB481WS/01

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood] [onSet(1)] TypeError: Cannot read properties of undefined (reading 'on')
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood] TypeError: Cannot read properties of undefined (reading 'on')
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at /homebridge/node_modules/homebridge-homeconnect/src/has-light.ts:61:38
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at Array.every (<anonymous>)
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at hasSettings (/homebridge/node_modules/homebridge-homeconnect/src/has-light.ts:61:17)
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at ApplianceHood.updateFanHC (/homebridge/node_modules/homebridge-homeconnect/src/has-light.ts:212:17)
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at Serialised.operation (/homebridge/node_modules/homebridge-homeconnect/src/has-fan.ts:139:88)
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at Serialised.startActive (/homebridge/node_modules/homebridge-homeconnect/src/serialised.ts:84:39)
[12/16/2023, 10:44:02 PM] [homebridge-homeconnect] [Hood]     at Serialised.startPending (/homebridge/node_modules/homebridge-homeconnect/src/serialised.ts:66:35)
```

### Configuration

```json
Nothing of interest.
```

### Additional Information

I did some cursory debugging to see if it would be something quick but its a bit deeper than I have time for at the moment. It appears that in `updateFanHC()`, all the following values are undefined. Dumped from some log statements I added:

> type: { percent: 50, active: 1 }
> settings undefined
> value undefined
> service undefined

I'm guessing something is happening in the original `makeSerialisedObject` call. If I have more time I'll try to dig into it, but hope this is enough to go on for now!

**Comment by thoukydides** [comment]
Please provide a full log with debug enabled for this issue.

The few lines of log provided relate to controlling the light, not the fan.

**Comment by thoukydides** [comment]
I think that I have spotted the problem - both `HasFan` and `HasLight` were defining `updateFanHC`. The latter should obviously be defining `updateLightHC` instead.

**Comment by thoukydides** [comment]
Please try v0.33.1.

(I do not have a Hood that supports Home Connect, so am unable to test this functionality myself.)

**Comment by DonutEspresso** [comment]
Thank you! v0.33.1 addresses the issue. Appreciate the super quick turn around. Thanks for all your help on this plugin. 👍
