### ISSUE TITLE
Does not support any programs - Coffee Maker

### ISSUE THREAD

**Issue by Tom2Drake** [thoukydides/homebridge-homeconnect#27]
#### Description of Issue
Since yesterday my siemens coffee maker no longer works with HomeKit. The Log say that the machine does not support any program.

#### Plugin Version
homebridge-homeconnect v0.18.1

#### Home Connect Appliance(s)
Siemens EQ9 plus connect TI9555X1DE/10

#### Log File

[5/28/2020, 14:31:49] [HomeConnect] Started events stream for all appliances
[5/28/2020, 14:31:49] [HomeConnect] Home Connect request #2: OK +612ms 
[5/28/2020, 14:31:49] [HomeConnect] Found 1 appliances
[5/28/2020, 14:31:49] [HomeConnect] Scheduling configuration schema write
[5/28/2020, 14:31:49] [HomeConnect] Connecting accessory 'Kaffeemaschine'
[5/28/2020, 14:31:49] [HomeConnect] [Kaffeemaschine] Siemens CoffeeMaker (E-Nr: TI9555X1DE/10)
[5/28/2020, 14:31:49] [HomeConnect] [Kaffeemaschine] Connected, so reading appliance state...
[5/28/2020, 14:31:49] [HomeConnect] Home Connect request #3: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110
[5/28/2020, 14:31:49] [HomeConnect] [Kaffeemaschine] Cache loaded (60 entries)
[5/28/2020, 14:31:49] [HomeConnect] [Kaffeemaschine] Cache 'Appliance power' [de-DE, updated 97497 seconds ago] is too old

[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #5: OK +1220ms 
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #6: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110/programs/selected
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #6: There is no program selected [SDK.Error.NoProgramSelected] +205ms 
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #7: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110/programs/active
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #7: There is no program active [SDK.Error.NoProgramActive] +160ms 
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] Successfully read all appliance state
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] connected=true (5 listeners)
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] Connected
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #8: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110/settings/BSH.Common.Setting.PowerState
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] Cache 'Appliance programs' [de-DE, updated 845 seconds ago]
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] Does not support any programs
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #9: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110/programs/available
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #9: OK +157ms 
[5/28/2020, 14:31:54] [HomeConnect] Scheduling configuration schema write
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] 'Program details' written to cache
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #8: Setting not found for HomeAppliance [SDK.Error.UnsupportedSetting] +194ms 
[5/28/2020, 14:31:54] [HomeConnect] [Kaffeemaschine] 'Appliance power' written to cache
[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Cache saved (60 entries)
[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Finished reading available program options
[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Invalid program configuration ignored: Program key 'ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso' is not supported by the appliance

[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Adding services for 0 programs
[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Removing services for 10 programs
[5/28/2020, 14:31:55] [HomeConnect] [Kaffeemaschine] Cache 'Appliance commands' [de-DE, updated 845 seconds ago]

[5/28/2020, 14:31:59] [HomeConnect] [Kaffeemaschine] Cache saved (60 entries)
[5/28/2020, 14:31:59] [HomeConnect] [Kaffeemaschine] Cannot read property 'constraints' of null
[5/28/2020, 14:31:59] [HomeConnect] [Kaffeemaschine] Initialising mixin 'HasPower'
[5/28/2020, 14:31:59] [HomeConnect] [Kaffeemaschine] TypeError: Cannot read property 'constraints' of null
    at ApplianceCoffeeMaker.init (/usr/lib/node_modules/homebridge-homeconnect/lib/has_power.js:47:30)
    at doInit (/usr/lib/node_modules/homebridge-homeconnect/lib/appliance_generic.js:253:21)

**Comment by thoukydides** [comment]
That log shows quite a few problems. It basically looks like the Home Connect API is not returning any state or capabilities for the appliance.

The most obvious is:
```
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #8: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E323110/settings/BSH.Common.Setting.PowerState
[5/28/2020, 14:31:54] [HomeConnect] Home Connect request #8: Setting not found for HomeAppliance [SDK.Error.UnsupportedSetting] +194ms
```

This particular setting should be supported by all appliances, even if it only supports `On`: https://developer.home-connect.com/docs/settings/power_state

Restarting my own homebridge instance I am seeing a massive number of errors from the Home Connect API
* `ESOCKETTIMEDOUT`
* `HomeAppliance did not respond in time. [SDK.Error.HomeAppliance.Connection.Initialization.Failed]`
* `502 - "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/api/homeappliances/SIEMENS-SN678D06TG-XXXXXXXXXXXX/settings\">GET&nbsp;/api/homeappliances/SIEMENS-SN678D06TG-XXXXXXXXXXXX/settings</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n</body></html>\n"`

Hence, it looks like the Home Connect servers are having serious problems. There isn't anything that I can do about that. If the plugin cannot even check whether the appliance is switched on then very little else is likely to work.

I suggest you wait a few hours and then try stopping homebridge, delete the cache files (see https://github.com/thoukydides/homebridge-homeconnect/wiki/Files#plugin-persistent-cache), and then restart homebridge.

**Comment by Tom2Drake** [comment]
yeah, it seems like the HomeConect servers are not that reliable .

**Comment by thoukydides** [comment]
In the absence of any official Home Connect server status I have knocked together my own, which you can find at: https://www.thouky.co.uk/homeconnect.html

They seem to be working properly for me now...

**Comment by Tom2Drake** [comment]
For me, it is still the same issue. Your Server status page is genuinely cool, they should hire you.

**Comment by thoukydides** [comment]
If you are still getting the `SDK.Error.UnsupportedSetting` error for the `GET ... BSH.Common.Setting.PowerState` then the only thing that I can suggest is to report it at https://developer.home-connect.com/support/contact

**Comment by thoukydides** [comment]
Great. :-)

Thanks for letting me know.
