### ISSUE TITLE
Home Connect Authorisation Failed

### ISSUE THREAD

**Issue by stalkerj** [thoukydides/homebridge-homeconnect#275]
### Description of Issue

I got this message right after entered Client ID.
I'm in Russia. Heared about blocking AWS few days ago. Can it be a reason of my problem or how can i fix it?
Original Home Connect works only with VPN
![image](https://github.com/thoukydides/homebridge-homeconnect/assets/17808225/5d000937-be31-4324-9f51-8bedd2d77f06)
![image](https://github.com/thoukydides/homebridge-homeconnect/assets/17808225/16056267-c2bf-4da1-a234-6b782003c8c9)

### Expected Behaviour

I got this message right after entered Client ID.

### Steps to Reproduce

just add Client id

### Plugin Version

latest

### Environment

- OS: Ubuntu Focal (20.04.4 LTS)
- Node: 20.12.2
- Homebridge: 1.7.0

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[4/18/2024, 11:06:13 PM] [HomeConnect] Attempting authorisation
[4/18/2024, 11:06:13 PM] [HomeConnect] Unable to use saved API authorisation (Error: No saved authorisation for this client)
[4/18/2024, 11:06:13 PM] [HomeConnect] Requesting authorisation using the Device Flow
[4/18/2024, 11:06:13 PM] [HomeConnect] Home Connect request #1: POST /security/oauth/device_authorization
[4/18/2024, 11:06:13 PM] [HomeConnect] Saving configuration schema data
[4/18/2024, 11:06:13 PM] [HomeConnect] Home Connect request #1: 403 Forbidden - <html>
[4/18/2024, 11:06:13 PM] [HomeConnect] <head><title>403 Forbidden</title></head>
[4/18/2024, 11:06:13 PM] [HomeConnect] <body>
[4/18/2024, 11:06:13 PM] [HomeConnect] <center><h1>403 Forbidden</h1></center>
[4/18/2024, 11:06:13 PM] [HomeConnect] </body>
[4/18/2024, 11:06:13 PM] [HomeConnect] </html>
[4/18/2024, 11:06:13 PM] [HomeConnect]  +552ms
[4/18/2024, 11:06:13 PM] [HomeConnect] Request will not be retried (status code 403)
[4/18/2024, 11:06:13 PM] [HomeConnect] [API authorisation] Home Connect Status Code Error: [403 Forbidden] <html>
[4/18/2024, 11:06:13 PM] [HomeConnect] <head><title>403 Forbidden</title></head>
[4/18/2024, 11:06:13 PM] [HomeConnect] <body>
[4/18/2024, 11:06:13 PM] [HomeConnect] <center><h1>403 Forbidden</h1></center>
[4/18/2024, 11:06:13 PM] [HomeConnect] </body>
[4/18/2024, 11:06:13 PM] [HomeConnect] </html>
[4/18/2024, 11:06:13 PM] [HomeConnect] 
[4/18/2024, 11:06:13 PM] [HomeConnect] POST /security/oauth/device_authorization
[4/18/2024, 11:06:13 PM] [HomeConnect] Home Connect Status Code Error: [403 Forbidden] <html>
[4/18/2024, 11:06:13 PM] [HomeConnect] <head><title>403 Forbidden</title></head>
[4/18/2024, 11:06:13 PM] [HomeConnect] <body>
[4/18/2024, 11:06:13 PM] [HomeConnect] <center><h1>403 Forbidden</h1></center>
[4/18/2024, 11:06:13 PM] [HomeConnect] </body>
[4/18/2024, 11:06:13 PM] [HomeConnect] </html>
[4/18/2024, 11:06:13 PM] [HomeConnect] 
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.requestCore (/homebridge/node_modules/homebridge-homeconnect/src/api-ua.ts:345:29)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.request (/homebridge/node_modules/homebridge-homeconnect/src/api-ua.ts:250:34)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.post (/homebridge/node_modules/homebridge-homeconnect/src/api-ua.ts:107:39)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.deviceFlow (/homebridge/node_modules/homebridge-homeconnect/src/api-ua-auth.ts:289:26)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.obtainAccessToken (/homebridge/node_modules/homebridge-homeconnect/src/api-ua-auth.ts:190:29)
[4/18/2024, 11:06:13 PM] [HomeConnect]     at APIAuthoriseUserAgent.authoriseUserAgent (/homebridge/node_modules/homebridge-homeconnect/src/api-ua-auth.ts:116:17)
[4/18/2024, 11:06:13 PM] [HomeConnect] Authorisation attempt abandoned; restart Homebridge to try again
```

### Configuration

```json
no
```

**Comment by thoukydides** [comment]
It looks like you have diagnosed the problem yourself. As you say, it appears that the Home Connect API is (understandably) blocked from Russia. That is not something that I can (or would want to) help bypass. I implement similar geo-blocks on websites that I operate.
