### ISSUE TITLE
Appliance not connected to Home Connect cloud servers

### ISSUE THREAD

**Issue by firebowl** [thoukydides/homebridge-homeconnect#40]
#### Description of Issue
I try to turn on the appliance via the Home app or the Eve app but it doesn't work. In the Home app, the power switch does nothing at all. In the Eve app the coffee maker is shown as inactive and I can't select anything except to query the ID and that works and the ID is also displayed in the Homebridge log.
I don't really need any programs, it would be enough for me to be able to switch on the machine.

#### Plugin Version
v0.19.0

#### Home Connect Appliance(s)
SIEMENS-TP507DX4-68A40E358788

>  "platform": "NukiBridge"
        },
        {
            "clientid": "XXX",
            "simulator": false,
            "language": {
                "api": "de-DE"
            },
            "SIEMENS-TP507DX4-68A40E358788": {
                "programs": []
            },
            "platform": "HomeConnect"

#### Log File

> [23.12.2020, 09:25:51] Loaded plugin: homebridge-homeconnect@0.19.0
[23.12.2020, 09:25:51] Registering platform 'homebridge-homeconnect.HomeConnect'
[23.12.2020, 09:25:51] Registering platform 'homebridge-homeconnect.HomeConnect'
[23.12.2020, 09:25:53] [HomeConnect] Initializing HomeConnect platform...
[23.12.2020, 09:25:53] [HomeConnect] Initializing HomeConnect platform...
[23.12.2020, 09:25:53] [HomeConnect] new HomeConnectPlatform
[23.12.2020, 09:25:53] [HomeConnect] new HomeConnectPlatform
[23.12.2020, 09:25:53] [HomeConnect] Restored 1 cached accessories
[23.12.2020, 09:25:53] [HomeConnect] Refreshing access token in 11212 seconds
[23.12.2020, 09:25:53] [HomeConnect] Starting events stream for all appliances
[23.12.2020, 09:25:53] [HomeConnect] Home Connect request #1: STREAM https://api.home-connect.com/api/homeappliances/events
[23.12.2020, 09:25:53] [HomeConnect] Home Connect request #2: GET https://api.home-connect.com/api/homeappliances
[23.12.2020, 09:25:53] [HomeConnect] Home Connect request #2: OK +281ms 
[23.12.2020, 09:25:53] [HomeConnect] Found 1 appliances
[23.12.2020, 09:25:53] [HomeConnect] Scheduling configuration schema write
[23.12.2020, 09:25:53] [HomeConnect] Connecting accessory 'Kaffeevollautomat'
[23.12.2020, 09:25:53] [HomeConnect] [Kaffeevollautomat] Siemens CoffeeMaker (E-Nr: TP507DX4/03)
[23.12.2020, 09:25:53] [HomeConnect] Started events stream for all appliances
[23.12.2020, 09:25:53] [HomeConnect] [Kaffeevollautomat] Event START (0 items)
[23.12.2020, 09:25:53] [HomeConnect] [Kaffeevollautomat] Connected, so reading appliance state...
[23.12.2020, 09:25:53] [HomeConnect] [Kaffeevollautomat] No cache found
[23.12.2020, 09:25:53] [HomeConnect] [Kaffeevollautomat] Cache 'Appliance power' does not exist in cache
[23.12.2020, 09:25:53] [HomeConnect] Home Connect request #3: GET https://api.home-connect.com/api/homeappliances/SIEMENS-TP507DX4-68A40E358788
[23.12.2020, 09:25:54] [HomeConnect] Home Connect request #3: OK +199ms 
[23.12.2020, 09:25:54] [HomeConnect] [Kaffeevollautomat] The appliance is offline
[23.12.2020, 09:25:54] [HomeConnect] [Kaffeevollautomat] GET status
[23.12.2020, 09:25:54] [HomeConnect] [Kaffeevollautomat] Error: The appliance is offline
 at HomeConnectDevice.requireConnected (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:545:19)
 at HomeConnectDevice.requireConnected (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:545:19)
 at HomeConnectDevice.requireConnected (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:545:19)
 at HomeConnectDevice.requireMonitor (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:558:14)
 at HomeConnectDevice.requireMonitor (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:558:14)
 at HomeConnectDevice.requireMonitor (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:558:14)
 at HomeConnectDevice.getStatus (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:105:18)
 at HomeConnectDevice.getStatus (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:105:18)
 at HomeConnectDevice.getStatus (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:105:18)
 at Array.<anonymous> (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:469:24)
 at Array.<anonymous> (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:469:24)
 at HomeConnectDevice.readAll (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:502:33)
 at HomeConnectDevice.readAll (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:502:33)
 at HomeConnectDevice.readAll (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_device.js:502:33)
[23.12.2020, 09:25:54] [HomeConnect] [Kaffeevollautomat] Ignoring appliance state read due to disconnection: The appliance is offline
[23.12.2020, 09:25:54] [HomeConnect] [Kaffeevollautomat] Appliance disconnected; abandoning 4 pending reads
[23.12.2020, 09:25:56] [HomeConnect] Scheduled configuration schema write complete
[23.12.2020, 09:26:45] [HomeConnect] [Kaffeevollautomat] Identify: SIEMENS-TP507DX4-68A40E358788
[23.12.2020, 09:26:45] [HomeConnect] [Kaffeevollautomat] Cache 'Appliance programs' does not exist in cache
[23.12.2020, 09:27:28] [HomeConnect] [Kaffeevollautomat] Identify: SIEMENS-TP507DX4-68A40E358788
[23.12.2020, 09:27:28] [HomeConnect] [Kaffeevollautomat] Cache 'Appliance programs' does not exist in cache
[23.12.2020, 09:27:54] [HomeConnect] [Kaffeevollautomat] Identify: SIEMENS-TP507DX4-68A40E358788
[23.12.2020, 09:27:54] [HomeConnect] [Kaffeevollautomat] Cache 'Appliance programs' does not exist in cache

**Comment by thoukydides** [comment]
It is pretty clear from the log that the Home Connect cloud servers are unable to communicate with your appliance. The plugin appears to be handling this problem appropriately.

Have you checked the connection status within the Home Connect app? (Go to the appliance, select Settings, and look for the Network section.)  It should look like this:
![Connected](https://user-images.githubusercontent.com/4775242/102979607-34042180-44fe-11eb-94b2-355e77ad908c.png)

If you don't see three green lines then try following the [Home Connect troubleshooting checklist](https://www.home-connect.com/global/help-support/set-up/faq#/Togglebox=7593076-7593170-2/). If that does not help then contact the [Home Connect service team](https://www.home-connect.com/global/service/contact-customer-service/customer-service).

Note that the Home Connect app is able to communicate directly with the appliances via your local network. It does not require a connection between the appliances and the Home Connect cloud servers. However, all third-party integrations (including this plugin) are only able to use the API provided by the cloud servers. Hence, whilst the Home Connect app being able to control the appliance is a good start (it indicates that the appliance has connected to your Wi-Fi access point) it is not sufficient to exclude the problem being with your appliance or network.

**Comment by thoukydides** [comment]
This is what the connection status looks like in the Home Connect app when the appliance is not connected to the cloud servers:
![Disconnected](https://user-images.githubusercontent.com/4775242/102980672-d375e400-44ff-11eb-940d-40a6426c9b19.png)

It looks like the Home Connect servers have been having a few problems this week. Unfortunately, there isn't an official service status page, but my own unofficial monitor shows that the `HomeAppliance is offline` error has been quite common over the last week: https://www.thouky.co.uk/homeconnect.html

Maybe just wait a few weeks for the Home Connect team to fix things at their end...

**Comment by firebowl** [comment]
Sorry, forgot to write that. In the Home Connect all lines are green and I can control the device. However, you have given me an idea. I deactivated the wifi on my phone for testing and immediately changed the display in the app. But not only the line from the phone to the machine became red but also the line from the machine to the cloud. 
Apparently the machine has no proper connection to the cloud. Strange only that everything is green, as soon as my phone is in the wifi.  https://www.deepl.com/translator#de/en/Sorry%2C%20hab%20vergessen%20das%20zu%20schreiben.%20In%20der%20Home%20%20Connect%20sind%20alle%20Linien%20gr%C3%BCn%20und%20ich%20kann%20das%20Ger%C3%A4t%20steuern.%20Allerdings%20hast%20Du%20mich%20auf%20eine%20Idee%20gebracht.%20Ich%20habe%20mal%20zum%20Testen%20das%20wlan%20an%20meinem%20Handy%20deaktiviert%20und%20sofort%20wechselte%20die%20Anzeige%20in%20der%20App.%20Es%20wurde%20aber%20nicht%20nur%20die%20Linie%20vom%20Handy%20zur%20Maschine%20rot%20sondern%20auch%20die%20Linie%20von%20der%20Maschine%20zur%20cloud.%20%0AScheinbar%20hat%20die%20Maschine%20keine%20richtige%20Verbindung%20zur%20cloud.%20Komisch%20nur%20das%20alles%20gr%C3%BCn%20ist%2C%20sobald%20mein%20Handy%20im%20wlan%20ist.%20
