### ISSUE TITLE
ExperimentalWarning - latest node/HB/plugin versions

### ISSUE THREAD

**Issue by fate8383** [thoukydides/homebridge-homeconnect#85]
[4/14/2022, 3:59:46 PM] [HomeConnect] Starting events stream for all appliances
(node:8182) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at new Blob (node:internal/blob:137:5)
    at Response.blob (/usr/lib/node_modules/homebridge-homeconnect/node_modules/undici/lib/fetch/body.js:292:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Response.text (/usr/lib/node_modules/homebridge-homeconnect/node_modules/undici/lib/fetch/body.js:301:18)
    at HomeConnectAPI.requestRaw (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_api.js:596:24)
    at HomeConnectAPI.requestAppliances (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_api.js:538:28)
    at HomeConnectAPI.getAppliances (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_api.js:90:20)
    at HomeConnectPlatform.updateAppliances (/usr/lib/node_modules/homebridge-homeconnect/index.js:133:34)

I am getting this after i add "--trace-warnings" as suggested in the logs. Does that mean anything that I should worry about?
Thanks

**Comment by thoukydides** [comment]
This is noted in the CHANGELOG.md file:
> Replaced used of request and request-promise-native (both deprecated since 11th February 2020) with undici. (This results in Node writing an ExperimentalWarning: buffer.Blob is an experimental feature message to the console, but this is safe to ignore.)

Just ignore the message.
