### ISSUE TITLE
Not able to authenticate: "Error: Cannot find module 'stream/promises'"

### ISSUE THREAD

**Issue by Babettestam** [thoukydides/homebridge-homeconnect#91]
#### Description of Issue
I do not retrieve the authentication URL in the logs, but instead see an error.

#### Plugin Version
homebridge-homeconnect v0.24.5

#### Log File

```
[6/23/2022, 4:34:04 PM] ERROR LOADING PLUGIN homebridge-homeconnect:
[6/23/2022, 4:34:04 PM] Error: Cannot find module 'stream/promises'
Require stack:
- /usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_api.js
- /usr/lib/node_modules/homebridge-homeconnect/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-homeconnect/lib/homeconnect_api.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

**Comment by thoukydides** [comment]
I am closing this issue due to the lack of feedback. It was almost certainly due to an incompatible version of Node.js being used.
